name: Publish resume in JSONResume format as Github Page

# Controls when the action will run. 
on:
  push:
    branches: [ master, main ]
    paths:
      - "resume.json"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build-resume:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v4
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: elegant
          resume_filepath: resume.json
          # modifies the index.html in-place
          output_filepath: docs/resume.html
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain docs/resume.html)" ]; then
            git add docs/resume.html
            git commit -m "[ci skip] chore(docs/resume.html): update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}

      - name: Update Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: 184483339270e7e76ecc72734c7f5d21
          file_path: resume.json
          file_type: text

  build-about:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v4
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: docs/about.md
          output: docs/index.html
          github-corners: false

